### ISSUE TITLE
mcp gyro readout fails after a few hours

### ISSUE THREAD

**Issue by fissel** [BlastTNG/flight#54]
After a few hours of reading gyro data mcp seems to lose the ability to read from the gyros.  

The plot below shows the gyro readout lost at 22:42 (UT) on 2015-DEC-13 (3 hours after mcp was started).  The fault_gy flag was not set and there were no corresponding error messages in the mcp log.  Gyro communication was recovered by restarting mcp.
![gyro_comm_lost_2015dec13](https://cloud.githubusercontent.com/assets/15033087/11770066/8dca2aea-a1c3-11e5-881f-5cbd5c15a47a.png)

**Comment by sethhillbrand** [comment]
Corrected behavior in cdcdb8c47a89e6d34bec468ed30830ee2b7556a9

The issue was that packets from the gryo boxes became "bursty" with multiple arriving in a short period with longer stretches in between.  Previous code handled one packet per interrupt.  Current code processes all packets received since the previous interrupt.

**Comment by sethhillbrand** [comment]
As an addendum to this, the streams could also be noisy, in which case the serial driver might receive a disconnect.  We handle this by closing and reconnecting to any stream that is outputting more than 2 packets worth of garbage
